---
- name: configuring tomcat using child playbooks and hostsscope varaibles
  hosts: all
  tasks: 
    - name: all multiple child playbooks
      include_tasks: "{{item}}"
      with_items: 
        - install-tomcat.yml
        - copy_tomcat.yml
        - change_port.yml
        - restart_tomcat.yml
        - pause.yml
        - check_tomcat_response.yml
...


