---
- name: create users and copy the files into users home dir
  hosts: all
  tasks:
    - name: create multiple users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: anu,b: anu,c: /tmp/anu}
        - {a: ravi,b: ravi,c: /home/ravi}
    - name: copy files into users home dirs
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
        owner: "{{item.c}}"
        group: "{{item.d}}"
        mode: "{{item.e}}"
      with_items:
       - {a: /etc/passwd,b: /tmp/anu,c: anu,d: ravi,e: 773}
       - {a: /etc/group,b: /home/ravi,c: ravi,d: anu,e: 700}
...         

