---
- name: using host scope varaibles
  hosts: 172.31.55.27
  tasks:
    - name: create user
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        home: "{{d}}"
        shell: "{{e}}"
        commnet: "{{f}}"
...          

